### ISSUE TITLE
[macOS/Skia.Gtk] [menu] Multiple items remain in focused state when scrolling in the left menu

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#118]
## Current behavior
Multiple items remain in selected state when scrolling in the left menu
![Screen Shot 2021-02-04 at 5 19 49 PM](https://user-images.githubusercontent.com/38770890/107043032-6f963a80-6790-11eb-801e-c73acfd281ef.png)

## Expected behavior
A focused state should be displayed only when cursor focus on the item

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu scroll to the bottom on the list
2. Scroll to the top
3. Notice some elements remain in a focused state

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
There seems to be multiple ways of reproducing this:
```
background color: red=pointerover, blue=pressed, green=ripple (part of pressed too)
  ^ red/green cannot co-exist, but green can co-exists(mixed) with red/green
extra textblocks: DefaultState=all visual states; DefaultPState=only pressed states; DefaultPOState=only pointerover states
some visual actifacts are due to recording from windows through vnc viewer & gif compression
```
- Hover + Mouse Scroll:
![20210205 macos nvi hover scroll](https://user-images.githubusercontent.com/2359550/107079497-f01f6000-67bd-11eb-8a1f-40fd6ee6a67e.gif)

- "Remote Hover": // no mouse button were held down during recording
![20210205 macos nvi hover offset](https://user-images.githubusercontent.com/2359550/107079563-04fbf380-67be-11eb-95bf-a7d105e272d6.gif)

**Comment by Xiaoy312** [comment]
<details>
 <summary>debug note</summary>

    so at the bottom of the callstack for NVI::OnPresenterPointerEntered is this monstrosity:
        *>Windows.UI.Xaml.Shapes.Ellipse-'ClickEllipse'-(1624x1624)@(0,0) ds:1624,1624 HA=Stretch,VA=StretchFE.Width=1624,FE.Height=1624 AvailableSize=1624,1624 Grp(System.Linq.Enumerable+SelectIListIterator`2[Windows.UI.Xaml.Media.Transform,System.String])
        ^ 1624x1624 absolute unit
        ^ this element is part of the `Ripple` template which is part of the `NVI` template...
    technically it should not receive PointerEvent in the first place
        since its direct parent `Canvas` has IsHitTestVisible=false
        even explicitly set IsHitTestVisible="False" on the Ellipse doesnt help neither
        \---
        when the pointer event arrived, the watcher tells that:
            this: Ellipse
            this.IsHitTestVisible: true
            (this.Parent as UIElement).IsHitTestVisible: true
            ^ ???
        \---
        XamlCodeGen did set them: IsHitTestVisible = false/* bool/, False, Canvas/IsHitTestVisible */,
        so is the style applied correct, since this showed up in watcher: Tag = @"TestValue312"/* object/, TestValue312, Ellipse/Tag */,

</details>

**Comment by MartinZikmund** [comment]
This happens even for the new MUX NavView, but it is a general problem that we have even in ListView for macOS.

**Comment by Xiaoy312** [comment]
fixed by: #5209

**Comment by sakshi173** [comment]
I retested the issue is still present. Below is the screenshot. Reopening the issue.
Note:- same issue is happening in Skia.GTk
**MacOS**
![multiple selection issue](https://user-images.githubusercontent.com/74563602/116926675-a31a2100-ac28-11eb-8dea-4b9bc45f4594.png)

**Skia**
![Skia multiple selection issue](https://user-images.githubusercontent.com/74563602/116926878-ed9b9d80-ac28-11eb-954f-8f25a2fdb25b.png)

**Comment by brswan** [comment]
Has there been any progress on this issue?  I've noticed that my GTK builds with Uno 4.6.39 has buttons that appear to have the pointer in a stuck up state.  The visual show either button over or button up even though other buttons are being pressed.

**Comment by Xiaoy312** [comment]
@brswan 
This issue has been deserted for awhile now. I just re-tested it on Skia.GTK and I was no longer able to reproduce the issue.
Can you share more about the bug you are experiencing, preferably [in a new issue](https://github.com/unoplatform/Uno.Gallery/issues/new?assignees=&labels=kind%2Fbug%2C+triage%2Funtriaged&template=bug-report.md)?

**Comment by Xiaoy312** [comment]
@sakshi173 Can you re-confirm the status of this bug? Thanks.
