### ISSUE TITLE
Leading space in most `TextBlock` samples

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#1196]
## Current behavior

Most `TextBlock` samples in Uno Gallery begin with a space, which makes them look misaligned.

## Expected behavior

Should not happen.

## How to reproduce it (as minimally and precisely as possible)

Open `TextBlock` samples in Uno Gallery and scroll down:

![Image](https://github.com/user-attachments/assets/8f5c3566-4136-4cf2-8b2b-d55d5645c513)

Notice the space is even included in the XAML samples:

![Image](https://github.com/user-attachments/assets/4a3a0cde-810d-471c-a811-fba7b4b41639)

## Environment

Nuget Package:

Package Version(s): latest dev

Affected platform(s):

All

Visual Studio 2022

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
duplicated of unoplatform/uno-private#1211 which should be fixed

it is now fixed for skia-wasm canary: https://white-field-08c5cf00f-canaryskia.eastus2.3.azurestaticapps.net/
note2self: sanity-check android/ios

**Comment by MartinZikmund** [comment]
@Xiaoy312 I think it is not yet fixed, from the canary link:

![Image](https://github.com/user-attachments/assets/b2bda03f-2fda-4bb4-8d0f-86eb95aa13fd)

I think this will be mainly a small sample issue as the samples themselves just contain a leading space in the `Text` property, which makes them display this way:

![Image](https://github.com/user-attachments/assets/ba682fc3-5bac-4dee-8357-3e0673ba439c)

**Comment by Xiaoy312** [comment]
There is two issues at play:
- the TextBlock content is rendered with an extra leading space
- ShowMeTheXaml showing extra indentations for text-literal in source code
